nodeSelector:
  nodegroup: management-nodes

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: management
    effect: "NoSchedule"

provisionDataStore:
  cassandra: false

allInOne:
  enabled: true
  replicas: 3
  image: docker.io/jaegertracing/all-in-one

storage:
  type: none

agent:
  enabled: false

collector:
  enabled: false

query:
  enabled: false
